=== bnicolae/blobseer/scripts/templates/ctrl_params.xsd
<?xml version="1.0"?>
<!-- $Id: ctrl_params.xsd 1751 2007-09-18 13:17:11Z lbreuil $ -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="ctrl_params">
	<xsd:complexType>
		<!-- all means 'in any order' -->
		<xsd:all>
			<xsd:element name="planner">
				<xsd:complexType>
					<xsd:attribute name="mode" type="planner_mode_t" use="required"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="envs" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="env" minOccurs="1" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="name"   type="xsd:string" use="required"/>
								<xsd:attribute name="value"  type="xsd:string" use="required"/>
								<xsd:attribute name="action" type="env_action_t" use="required"/>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="submission_method">
				<xsd:complexType>
					<xsd:attribute name="name" type="submeth_name_t" use="required"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="transfer_files">
				<xsd:complexType>
					<xsd:attribute name="method" type="method_t" use="required"/>
					<xsd:attribute name="type" type="xsd:string"/> <!-- either all, or a comma-separated list of cfg,data,exe,lib,so -->
					<xsd:attribute name="binlib_in_commondir" type="xsd:boolean"/>
					<xsd:attribute name="destdir" type="destdir_t"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="launch_gdb" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="launch_window" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="size" type="xsd:integer" use="required"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="placement_constraints" type="placement_constraints_t" minOccurs="0"/>
			<!-- for plugins -->
			<xsd:element name="plugin" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="name" type="xsd:string" use="required"/>
					<xsd:attribute name="file" type="xsd:string" use="required"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:all>
	</xsd:complexType>
</xsd:element>

<xsd:simpleType name="env_action_t">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="add"/>
		<xsd:enumeration value="set"/>
	</xsd:restriction>
</xsd:simpleType>


<xsd:simpleType name="planner_mode_t">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="h_rand_rand"/>
		<xsd:enumeration value="h_rand_powr"/>
		<xsd:enumeration value="h_rand_comm"/>
		<xsd:enumeration value="h_rand_gree"/>
		<xsd:enumeration value="h_work_rand"/>
		<xsd:enumeration value="h_work_powr"/>
		<xsd:enumeration value="h_work_comm"/>
		<xsd:enumeration value="h_work_gree"/>
		<xsd:enumeration value="h_gath_rand"/>
		<xsd:enumeration value="h_gath_powr"/>
		<xsd:enumeration value="h_gath_comm"/>
		<xsd:enumeration value="h_gath_gree"/>
		<xsd:enumeration value="h_affinity"/>
		<xsd:enumeration value="random"/>
		<xsd:enumeration value="RR"/>
	</xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="submeth_name_t">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="ssh"/>
		<xsd:enumeration value="rsh"/>
		<xsd:enumeration value="oarsh"/>
	</xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="method_t">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="scp"/>
		<xsd:enumeration value="rcp"/>
		<xsd:enumeration value="oarcp"/>
	</xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="destdir_t">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="shared"/>
		<xsd:enumeration value="scratch"/>
	</xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="association_type_t">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="pattern"/>
		<xsd:enumeration value="exact"/>
	</xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="placement_constraints_t">
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			associate => constraint placement of a process group (TODO: process !) to a set of nodes
			('pattern_match'), or a precise node ('exact_match'). unassociate is the opposite.
			collocate => assure that two process group (TODO: process !) will try to share the same
			set of nodes. separate is the opposite.
		</xsd:documentation>
	</xsd:annotation>
	<xsd:sequence>
		<xsd:element name="associate" minOccurs="0" maxOccurs="unbounded">
			<xsd:complexType>
				<xsd:attribute name="id" type="xsd:IDREF" use="required"/>
				<xsd:attribute name="id_type" type="association_type_t" use="required"/>
				<xsd:attribute name="match" type="xsd:string" use="required"/>
				<xsd:attribute name="match_type" type="association_type_t" use="required"/>
			</xsd:complexType>
		</xsd:element>
		<xsd:element name="unassociate" minOccurs="0" maxOccurs="unbounded">
			<xsd:complexType>
				<xsd:attribute name="id" type="xsd:IDREF" use="required"/>
				<xsd:attribute name="id_type" type="association_type_t" use="required"/>
				<xsd:attribute name="match" type="xsd:string" use="required"/>
				<xsd:attribute name="match_type" type="association_type_t" use="required"/>
			</xsd:complexType>
		</xsd:element>
		<xsd:element name="collocate" minOccurs="0" maxOccurs="unbounded">
			<xsd:complexType>
				<xsd:attribute name="id" type="xsd:IDREF" use="required"/>
				<xsd:attribute name="with" type="xsd:IDREF" use="required"/>
			</xsd:complexType>
		</xsd:element>
		<xsd:element name="separate" minOccurs="0" maxOccurs="unbounded">
			<xsd:complexType>
				<xsd:attribute name="id" type="xsd:IDREF" use="required"/>
				<xsd:attribute name="from" type="xsd:IDREF" use="required"/>
			</xsd:complexType>
		</xsd:element>
	</xsd:sequence>
</xsd:complexType>
</xsd:schema>

=== bnicolae/blobseer/scripts/templates/oarsh-ctrl.xml
<?xml version='1.0'?>
<!DOCTYPE ctrl_params>
<!-- SYSTEM "../dtd/ctrl_params.dtd" -->
<ctrl_params xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ctrl_params.xsd">
	<submission_method name="oarsh"/>
	<transfer_files method="oarcp" type="data,exe" binlib_in_commondir="false" destdir="scratch" />
	<envs>
	    <env name="LD_LIBRARY_PATH" value="${LD_LIBRARY_PATH}" action="add"/>
	    <env name="CLASSPATH" value="${CLASSPATH}" action="add"/>
	</envs>	
	<planner mode="RR"/>
	<placement_constraints> ${placement_constraints} </placement_constraints>
</ctrl_params>
